-- EnemyData.lua
-- Complete enemy roster: Normal, Elite, and Boss tiers across 3 spawn zones.
-- Each enemy has visual specs, AI attack type, and drop values.
-- attackType: "melee" | "charge" | "ranged" | "aoe"

local EnemyData = {}

-- ─────────────────────────────────────────
-- Tier constants
-- ─────────────────────────────────────────
EnemyData.Tier = {
	Normal = "Normal",
	Elite  = "Elite",
	Boss   = "Boss",
}

-- ─────────────────────────────────────────
-- Attack type definitions (used by EnemyManager AI)
-- melee  : chase + bite when in range
-- charge : wind-up then dash/lunge at player
-- ranged : maintain distance, spit projectile
-- aoe    : stomp / pulse that damages in radius (boss/elite only)
-- ─────────────────────────────────────────

-- ─────────────────────────────────────────
-- ZONE: Grassland  (center-forest region)
-- ─────────────────────────────────────────
EnemyData.Grassland = {

	-- ── Normal ───────────────────────────
	{
		key         = "Aphid",
		displayName = "Aphid",
		tier        = "Normal",
		health      = 28,
		damage      = 6,
		speed       = 17,
		attackRange = 4,
		attackRate  = 1.2,
		xpReward    = 12,
		crystalDrop = 2,
		size        = 0.45,
		-- Visual
		bodyColor   = Color3.fromRGB(120, 210, 80),
		accentColor = Color3.fromRGB(80, 160, 40),
		shape       = "Sphere",
		emoji       = "🟢",
		attackType  = "melee",
		-- AI
		aggroRange  = 22,
		groupSize   = 5,   -- spawns in groups
	},
	{
		key         = "Earwig",
		displayName = "Earwig",
		tier        = "Normal",
		health      = 75,
		damage      = 16,
		speed       = 10,
		attackRange = 5,
		attackRate  = 1.8,
		xpReward    = 30,
		crystalDrop = 5,
		size        = 0.85,
		bodyColor   = Color3.fromRGB(100, 55, 20),
		accentColor = Color3.fromRGB(60, 30, 10),
		shape       = "Block",
		emoji       = "🟤",
		attackType  = "melee",
		aggroRange  = 20,
		groupSize   = 1,
	},
	{
		key         = "Grasshopper",
		displayName = "Grasshopper",
		tier        = "Normal",
		health      = 95,
		damage      = 22,
		speed       = 14,
		attackRange = 8,
		attackRate  = 2.5,
		xpReward    = 45,
		crystalDrop = 7,
		size        = 1.0,
		bodyColor   = Color3.fromRGB(80, 180, 40),
		accentColor = Color3.fromRGB(140, 220, 80),
		shape       = "Block",
		emoji       = "🦗",
		attackType  = "charge",
		aggroRange  = 28,
		groupSize   = 1,
		chargeWindup = 1.2,   -- seconds before charge
		chargePower  = 80,    -- impulse force
	},

	-- ── Elite ────────────────────────────
	{
		key         = "AlphaEarwig",
		displayName = "Alpha Earwig",
		tier        = "Elite",
		health      = 300,
		damage      = 42,
		speed       = 12,
		attackRange = 6,
		attackRate  = 1.4,
		xpReward    = 130,
		crystalDrop = 28,
		size        = 1.5,
		bodyColor   = Color3.fromRGB(80, 40, 10),
		accentColor = Color3.fromRGB(220, 180, 40),   -- gold trim
		shape       = "Block",
		emoji       = "⭐",
		attackType  = "melee",
		aggroRange  = 30,
		groupSize   = 1,
		eliteAura   = Color3.fromRGB(220, 160, 20),
	},
	{
		key         = "GiantAphid",
		displayName = "Giant Aphid",
		tier        = "Elite",
		health      = 210,
		damage      = 32,
		speed       = 13,
		attackRange = 18,
		attackRate  = 2.0,
		xpReward    = 100,
		crystalDrop = 22,
		size        = 1.3,
		bodyColor   = Color3.fromRGB(60, 180, 40),
		accentColor = Color3.fromRGB(180, 255, 100),
		shape       = "Sphere",
		emoji       = "⭐",
		attackType  = "ranged",
		aggroRange  = 35,
		groupSize   = 1,
		projectileColor = Color3.fromRGB(100, 230, 50),
		projectileSpeed = 50,
		eliteAura   = Color3.fromRGB(100, 220, 60),
	},

	-- ── Boss ─────────────────────────────
	{
		key         = "MantisOverlord",
		displayName = "Mantis Overlord",
		tier        = "Boss",
		health      = 2500,
		damage      = 85,
		speed       = 10,
		attackRange = 12,
		attackRate  = 2.5,
		xpReward    = 550,
		crystalDrop = 160,
		size        = 3.0,
		bodyColor   = Color3.fromRGB(40, 140, 30),
		accentColor = Color3.fromRGB(200, 50, 50),
		shape       = "Block",
		emoji       = "💀",
		attackType  = "aoe",   -- switches based on HP phase
		aggroRange  = 60,
		groupSize   = 1,
		-- Phase thresholds (fraction of maxHP)
		phases      = {
			{ hpFrac = 1.0,  attackType = "ranged", speed = 10 },
			{ hpFrac = 0.66, attackType = "charge",  speed = 12 },
			{ hpFrac = 0.33, attackType = "aoe",     speed = 14 },
		},
		projectileColor  = Color3.fromRGB(80, 255, 80),
		projectileSpeed  = 60,
		chargeWindup     = 1.5,
		chargePower      = 120,
		aoeRadius        = 14,
		aoeDamageScale   = 0.6,   -- fraction of base damage per AOE tick
		respawnDelay     = 300,   -- 5 minutes
		bossThemeColor   = Color3.fromRGB(30, 120, 20),
	},
}

-- ─────────────────────────────────────────
-- ZONE: Wetland  (near the pond, east side)
-- ─────────────────────────────────────────
EnemyData.Wetland = {

	-- ── Normal ───────────────────────────
	{
		key         = "WaterStrider",
		displayName = "Water Strider",
		tier        = "Normal",
		health      = 48,
		damage      = 11,
		speed       = 20,
		attackRange = 4,
		attackRate  = 1.0,
		xpReward    = 22,
		crystalDrop = 3,
		size        = 0.6,
		bodyColor   = Color3.fromRGB(50, 140, 180),
		accentColor = Color3.fromRGB(100, 200, 230),
		shape       = "Block",
		emoji       = "💧",
		attackType  = "melee",
		aggroRange  = 24,
		groupSize   = 3,
	},
	{
		key         = "PondLeech",
		displayName = "Pond Leech",
		tier        = "Normal",
		health      = 65,
		damage      = 13,
		speed       = 7,
		attackRange = 4,
		attackRate  = 1.5,
		xpReward    = 28,
		crystalDrop = 4,
		size        = 0.75,
		bodyColor   = Color3.fromRGB(100, 20, 20),
		accentColor = Color3.fromRGB(60, 10, 10),
		shape       = "Cylinder",
		emoji       = "🔴",
		attackType  = "melee",
		aggroRange  = 16,
		groupSize   = 2,
		dotDamage   = 4,    -- damage per second applied as a DoT
		dotDuration = 3,
	},
	{
		key         = "DivingBeetle",
		displayName = "Diving Beetle",
		tier        = "Normal",
		health      = 115,
		damage      = 24,
		speed       = 12,
		attackRange = 6,
		attackRate  = 2.0,
		xpReward    = 52,
		crystalDrop = 8,
		size        = 1.0,
		bodyColor   = Color3.fromRGB(20, 40, 100),
		accentColor = Color3.fromRGB(60, 90, 180),
		shape       = "Block",
		emoji       = "🔵",
		attackType  = "charge",
		aggroRange  = 26,
		groupSize   = 1,
		chargeWindup = 1.0,
		chargePower  = 90,
	},

	-- ── Elite ────────────────────────────
	{
		key         = "ElderStrider",
		displayName = "Elder Water Strider",
		tier        = "Elite",
		health      = 230,
		damage      = 36,
		speed       = 22,
		attackRange = 5,
		attackRate  = 1.0,
		xpReward    = 115,
		crystalDrop = 24,
		size        = 1.4,
		bodyColor   = Color3.fromRGB(30, 100, 150),
		accentColor = Color3.fromRGB(180, 220, 255),
		shape       = "Block",
		emoji       = "⭐",
		attackType  = "melee",
		aggroRange  = 32,
		groupSize   = 1,
		stunOnHit   = 0.8,   -- stun duration in seconds
		eliteAura   = Color3.fromRGB(80, 180, 255),
	},
	{
		key         = "BloatedLeech",
		displayName = "Bloated Leech",
		tier        = "Elite",
		health      = 360,
		damage      = 28,
		speed       = 6,
		attackRange = 12,
		attackRate  = 3.0,
		xpReward    = 140,
		crystalDrop = 30,
		size        = 1.8,
		bodyColor   = Color3.fromRGB(140, 30, 30),
		accentColor = Color3.fromRGB(220, 80, 80),
		shape       = "Sphere",
		emoji       = "⭐",
		attackType  = "aoe",
		aggroRange  = 28,
		groupSize   = 1,
		aoeRadius   = 12,
		aoeDamageScale = 0.8,
		dotDamage   = 6,
		dotDuration = 4,
		eliteAura   = Color3.fromRGB(200, 50, 50),
	},

	-- ── Boss ─────────────────────────────
	{
		key         = "DragonFlyWarlord",
		displayName = "Dragonfly Warlord",
		tier        = "Boss",
		health      = 3000,
		damage      = 95,
		speed       = 18,
		attackRange = 20,
		attackRate  = 2.0,
		xpReward    = 650,
		crystalDrop = 200,
		size        = 3.5,
		bodyColor   = Color3.fromRGB(20, 80, 160),
		accentColor = Color3.fromRGB(80, 200, 255),
		shape       = "Block",
		emoji       = "💀",
		attackType  = "ranged",
		aggroRange  = 65,
		groupSize   = 1,
		phases      = {
			{ hpFrac = 1.0,  attackType = "ranged", speed = 18 },
			{ hpFrac = 0.66, attackType = "charge",  speed = 22 },
			{ hpFrac = 0.33, attackType = "aoe",     speed = 26 },
		},
		projectileColor  = Color3.fromRGB(50, 180, 255),
		projectileSpeed  = 75,
		chargeWindup     = 0.8,
		chargePower      = 150,
		aoeRadius        = 16,
		aoeDamageScale   = 0.5,
		respawnDelay     = 360,
		bossThemeColor   = Color3.fromRGB(20, 100, 200),
	},
}

-- ─────────────────────────────────────────
-- ZONE: Mushroom Hollow  (upper-left, dark mushroom biome)
-- ─────────────────────────────────────────
EnemyData.Mushroom = {

	-- ── Normal ───────────────────────────
	{
		key         = "FungusGnat",
		displayName = "Fungus Gnat",
		tier        = "Normal",
		health      = 22,
		damage      = 7,
		speed       = 15,
		attackRange = 4,
		attackRate  = 1.0,
		xpReward    = 10,
		crystalDrop = 2,
		size        = 0.4,
		bodyColor   = Color3.fromRGB(120, 50, 160),
		accentColor = Color3.fromRGB(180, 100, 220),
		shape       = "Sphere",
		emoji       = "🟣",
		attackType  = "melee",
		aggroRange  = 20,
		groupSize   = 6,
	},
	{
		key         = "PillBugRoller",
		displayName = "Pill Bug",
		tier        = "Normal",
		health      = 130,
		damage      = 20,
		speed       = 11,
		attackRange = 6,
		attackRate  = 2.2,
		xpReward    = 55,
		crystalDrop = 9,
		size        = 1.0,
		bodyColor   = Color3.fromRGB(100, 100, 120),
		accentColor = Color3.fromRGB(160, 160, 180),
		shape       = "Sphere",
		emoji       = "⚫",
		attackType  = "charge",
		aggroRange  = 22,
		groupSize   = 1,
		chargeWindup = 0.8,
		chargePower  = 100,
	},
	{
		key         = "Glowworm",
		displayName = "Glowworm",
		tier        = "Normal",
		health      = 58,
		damage      = 15,
		speed       = 9,
		attackRange = 20,
		attackRate  = 2.8,
		xpReward    = 36,
		crystalDrop = 6,
		size        = 0.7,
		bodyColor   = Color3.fromRGB(180, 255, 80),
		accentColor = Color3.fromRGB(220, 255, 120),
		shape       = "Cylinder",
		emoji       = "🟡",
		attackType  = "ranged",
		aggroRange  = 30,
		groupSize   = 2,
		projectileColor = Color3.fromRGB(220, 255, 80),
		projectileSpeed = 45,
	},

	-- ── Elite ────────────────────────────
	{
		key         = "ToxicFungusBeetle",
		displayName = "Toxic Fungus Beetle",
		tier        = "Elite",
		health      = 310,
		damage      = 46,
		speed       = 9,
		attackRange = 8,
		attackRate  = 1.8,
		xpReward    = 145,
		crystalDrop = 32,
		size        = 1.6,
		bodyColor   = Color3.fromRGB(60, 100, 20),
		accentColor = Color3.fromRGB(140, 220, 40),
		shape       = "Block",
		emoji       = "⭐",
		attackType  = "aoe",
		aggroRange  = 25,
		groupSize   = 1,
		aoeRadius   = 8,
		aoeDamageScale = 0.7,
		dotDamage   = 5,
		dotDuration = 5,
		eliteAura   = Color3.fromRGB(100, 200, 30),
	},
	{
		key         = "MyceliumCentipede",
		displayName = "Mycelium Centipede",
		tier        = "Elite",
		health      = 260,
		damage      = 52,
		speed       = 18,
		attackRange = 5,
		attackRate  = 1.0,
		xpReward    = 165,
		crystalDrop = 36,
		size        = 1.4,
		bodyColor   = Color3.fromRGB(80, 30, 80),
		accentColor = Color3.fromRGB(200, 80, 200),
		shape       = "Block",
		emoji       = "⭐",
		attackType  = "charge",
		aggroRange  = 30,
		groupSize   = 1,
		chargeWindup = 0.6,
		chargePower  = 130,
		eliteAura   = Color3.fromRGB(180, 60, 180),
	},

	-- ── Boss ─────────────────────────────
	{
		key         = "SporeTitan",
		displayName = "Spore Titan",
		tier        = "Boss",
		health      = 3500,
		damage      = 105,
		speed       = 7,
		attackRange = 18,
		attackRate  = 3.5,
		xpReward    = 800,
		crystalDrop = 240,
		size        = 4.0,
		bodyColor   = Color3.fromRGB(80, 40, 20),
		accentColor = Color3.fromRGB(160, 80, 200),
		shape       = "Sphere",
		emoji       = "💀",
		attackType  = "aoe",
		aggroRange  = 60,
		groupSize   = 1,
		phases      = {
			{ hpFrac = 1.0,  attackType = "aoe",    speed = 7 },
			{ hpFrac = 0.66, attackType = "ranged",  speed = 9 },
			{ hpFrac = 0.33, attackType = "charge",  speed = 11 },
		},
		projectileColor  = Color3.fromRGB(180, 80, 255),
		projectileSpeed  = 40,
		chargeWindup     = 2.0,
		chargePower      = 90,
		aoeRadius        = 20,
		aoeDamageScale   = 0.4,
		respawnDelay     = 420,
		bossThemeColor   = Color3.fromRGB(100, 40, 140),
		dotDamage        = 8,   -- spore cloud DoT
		dotDuration      = 5,
	},
}

-- ─────────────────────────────────────────
-- ZONE: Volcanic Cavern  (Level 30–40)
-- Fire-themed, high DoT, aggressive mobs
-- ─────────────────────────────────────────
EnemyData.Volcanic = {

	-- ── Normal ───────────────────────────
	{
		key         = "EmberBeetle",
		displayName = "Ember Beetle",
		tier        = "Normal",
		health      = 260,
		damage      = 38,
		speed       = 13,
		attackRange = 5,
		attackRate  = 1.6,
		xpReward    = 80,
		crystalDrop = 14,
		size        = 1.0,
		bodyColor   = Color3.fromRGB(180, 60, 10),
		accentColor = Color3.fromRGB(255, 160, 40),
		shape       = "Block",
		emoji       = "🔥",
		attackType  = "melee",
		aggroRange  = 22,
		groupSize   = 1,
		dotDamage   = 5,
		dotDuration = 3,
	},
	{
		key         = "FireCentipede",
		displayName = "Fire Centipede",
		tier        = "Normal",
		health      = 200,
		damage      = 44,
		speed       = 17,
		attackRange = 6,
		attackRate  = 1.2,
		xpReward    = 90,
		crystalDrop = 16,
		size        = 1.2,
		bodyColor   = Color3.fromRGB(200, 40, 10),
		accentColor = Color3.fromRGB(255, 120, 10),
		shape       = "Block",
		emoji       = "🐛",
		attackType  = "charge",
		aggroRange  = 26,
		groupSize   = 2,
		chargeWindup = 0.9,
		chargePower  = 110,
	},
	{
		key         = "LavaSlug",
		displayName = "Lava Slug",
		tier        = "Normal",
		health      = 180,
		damage      = 32,
		speed       = 7,
		attackRange = 22,
		attackRate  = 2.5,
		xpReward    = 75,
		crystalDrop = 12,
		size        = 0.9,
		bodyColor   = Color3.fromRGB(160, 30, 0),
		accentColor = Color3.fromRGB(255, 80, 0),
		shape       = "Cylinder",
		emoji       = "🐌",
		attackType  = "ranged",
		aggroRange  = 32,
		groupSize   = 2,
		projectileColor = Color3.fromRGB(255, 100, 0),
		projectileSpeed = 48,
		dotDamage   = 7,
		dotDuration = 4,
	},

	-- ── Elite ────────────────────────────
	{
		key         = "MagmaWasp",
		displayName = "Magma Wasp",
		tier        = "Elite",
		health      = 900,
		damage      = 80,
		speed       = 22,
		attackRange = 20,
		attackRate  = 1.8,
		xpReward    = 340,
		crystalDrop = 75,
		size        = 1.6,
		bodyColor   = Color3.fromRGB(220, 80, 0),
		accentColor = Color3.fromRGB(255, 220, 30),
		shape       = "Block",
		emoji       = "⭐",
		attackType  = "ranged",
		aggroRange  = 40,
		groupSize   = 1,
		projectileColor = Color3.fromRGB(255, 150, 0),
		projectileSpeed = 65,
		dotDamage   = 10,
		dotDuration = 5,
		eliteAura   = Color3.fromRGB(255, 120, 0),
	},
	{
		key         = "InfernoMantis",
		displayName = "Inferno Mantis",
		tier        = "Elite",
		health      = 1100,
		damage      = 110,
		speed       = 14,
		attackRange = 8,
		attackRate  = 1.2,
		xpReward    = 420,
		crystalDrop = 90,
		size        = 2.0,
		bodyColor   = Color3.fromRGB(140, 30, 10),
		accentColor = Color3.fromRGB(255, 80, 20),
		shape       = "Block",
		emoji       = "⭐",
		attackType  = "melee",
		aggroRange  = 36,
		groupSize   = 1,
		eliteAura   = Color3.fromRGB(255, 60, 0),
	},

	-- ── Boss ─────────────────────────────
	{
		key         = "PyroclastQueen",
		displayName = "Pyroclast Queen",
		tier        = "Boss",
		health      = 8000,
		damage      = 200,
		speed       = 9,
		attackRange = 16,
		attackRate  = 2.8,
		xpReward    = 1800,
		crystalDrop = 500,
		size        = 4.0,
		bodyColor   = Color3.fromRGB(120, 20, 0),
		accentColor = Color3.fromRGB(255, 100, 0),
		shape       = "Block",
		emoji       = "💀",
		attackType  = "aoe",
		aggroRange  = 65,
		groupSize   = 1,
		phases      = {
			{ hpFrac = 1.0,  attackType = "ranged", speed =  9 },
			{ hpFrac = 0.66, attackType = "aoe",    speed = 11 },
			{ hpFrac = 0.33, attackType = "charge", speed = 14 },
		},
		projectileColor = Color3.fromRGB(255, 80, 0),
		projectileSpeed = 55,
		chargeWindup    = 1.8,
		chargePower     = 160,
		aoeRadius       = 22,
		aoeDamageScale  = 0.5,
		dotDamage       = 12,
		dotDuration     = 6,
		respawnDelay    = 480,
		bossThemeColor  = Color3.fromRGB(180, 40, 0),
	},
}

-- ─────────────────────────────────────────
-- ZONE: Crystal Abyss  (Level 40–50)
-- Void-themed, high burst damage, disorienting mobs
-- ─────────────────────────────────────────
EnemyData.Crystal = {

	-- ── Normal ───────────────────────────
	{
		key         = "CrystalScorpion",
		displayName = "Crystal Scorpion",
		tier        = "Normal",
		health      = 400,
		damage      = 60,
		speed       = 16,
		attackRange = 6,
		attackRate  = 1.4,
		xpReward    = 130,
		crystalDrop = 22,
		size        = 1.1,
		bodyColor   = Color3.fromRGB(80, 180, 220),
		accentColor = Color3.fromRGB(160, 240, 255),
		shape       = "Block",
		emoji       = "🦂",
		attackType  = "melee",
		aggroRange  = 24,
		groupSize   = 1,
		dotDamage   = 8,
		dotDuration = 4,
	},
	{
		key         = "VoidMoth",
		displayName = "Void Moth",
		tier        = "Normal",
		health      = 320,
		damage      = 55,
		speed       = 18,
		attackRange = 25,
		attackRate  = 2.0,
		xpReward    = 120,
		crystalDrop = 20,
		size        = 0.9,
		bodyColor   = Color3.fromRGB(40, 10, 80),
		accentColor = Color3.fromRGB(160, 80, 255),
		shape       = "Sphere",
		emoji       = "🦋",
		attackType  = "ranged",
		aggroRange  = 35,
		groupSize   = 3,
		projectileColor = Color3.fromRGB(140, 60, 255),
		projectileSpeed = 70,
	},
	{
		key         = "AbyssCrawler",
		displayName = "Abyss Crawler",
		tier        = "Normal",
		health      = 480,
		damage      = 70,
		speed       = 14,
		attackRange = 8,
		attackRate  = 1.8,
		xpReward    = 140,
		crystalDrop = 24,
		size        = 1.3,
		bodyColor   = Color3.fromRGB(20, 10, 40),
		accentColor = Color3.fromRGB(100, 40, 180),
		shape       = "Block",
		emoji       = "🕷️",
		attackType  = "charge",
		aggroRange  = 28,
		groupSize   = 1,
		chargeWindup = 0.7,
		chargePower  = 140,
	},

	-- ── Elite ────────────────────────────
	{
		key         = "PrismBeetle",
		displayName = "Prism Beetle",
		tier        = "Elite",
		health      = 1800,
		damage      = 130,
		speed       = 10,
		attackRange = 14,
		attackRate  = 2.2,
		xpReward    = 580,
		crystalDrop = 140,
		size        = 2.0,
		bodyColor   = Color3.fromRGB(100, 220, 240),
		accentColor = Color3.fromRGB(200, 255, 255),
		shape       = "Block",
		emoji       = "⭐",
		attackType  = "aoe",
		aggroRange  = 32,
		groupSize   = 1,
		aoeRadius   = 14,
		aoeDamageScale = 0.7,
		eliteAura   = Color3.fromRGB(100, 220, 255),
	},
	{
		key         = "QuantumSpider",
		displayName = "Quantum Spider",
		tier        = "Elite",
		health      = 1400,
		damage      = 160,
		speed       = 26,
		attackRange = 7,
		attackRate  = 0.9,
		xpReward    = 650,
		crystalDrop = 160,
		size        = 1.8,
		bodyColor   = Color3.fromRGB(60, 20, 100),
		accentColor = Color3.fromRGB(180, 100, 255),
		shape       = "Block",
		emoji       = "⭐",
		attackType  = "melee",
		aggroRange  = 38,
		groupSize   = 1,
		eliteAura   = Color3.fromRGB(160, 80, 255),
	},

	-- ── Boss ─────────────────────────────
	{
		key         = "VoidEmperor",
		displayName = "Void Emperor",
		tier        = "Boss",
		health      = 15000,
		damage      = 320,
		speed       = 11,
		attackRange = 22,
		attackRate  = 2.5,
		xpReward    = 3500,
		crystalDrop = 900,
		size        = 5.0,
		bodyColor   = Color3.fromRGB(10, 5, 30),
		accentColor = Color3.fromRGB(180, 80, 255),
		shape       = "Sphere",
		emoji       = "💀",
		attackType  = "ranged",
		aggroRange  = 70,
		groupSize   = 1,
		phases      = {
			{ hpFrac = 1.0,  attackType = "ranged", speed = 11 },
			{ hpFrac = 0.66, attackType = "charge", speed = 14 },
			{ hpFrac = 0.33, attackType = "aoe",    speed = 16 },
		},
		projectileColor = Color3.fromRGB(160, 60, 255),
		projectileSpeed = 85,
		chargeWindup    = 1.0,
		chargePower     = 200,
		aoeRadius       = 25,
		aoeDamageScale  = 0.4,
		dotDamage       = 15,
		dotDuration     = 6,
		respawnDelay    = 600,
		bossThemeColor  = Color3.fromRGB(80, 20, 160),
	},
}

-- ─────────────────────────────────────────
-- Flat lookup by key (for EnemyManager)
-- ─────────────────────────────────────────
EnemyData.ByKey = {}
for _, zoneList in pairs({
	EnemyData.Grassland, EnemyData.Wetland, EnemyData.Mushroom,
	EnemyData.Volcanic,  EnemyData.Crystal,
}) do
	for _, def in ipairs(zoneList) do
		EnemyData.ByKey[def.key] = def
	end
end

-- Tier spawn weights (used when randomly picking an enemy from a zone)
EnemyData.TierWeights = {
	Normal = 70,
	Elite  = 22,
	Boss   = 8,   -- controlled separately by EnemyManager, but listed for reference
}

return EnemyData
